#spring.application.name=Customer

spring:
  application:
    name : Customer
  datasource:
    url: jdbc:mysql://localhost:3306/bookserv?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Owais@9354
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: INFO
    com.ust.bookmanage: DEBUG # Adjust this to the package you want to debug
  file:
    name: logs/app.log # Logs will be written to this file
  pattern:
    console:
      logback:
        pattern: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    file:
      logback:
        pattern: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
server:
  port: 8081

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/